Feature/21
neonadeuri/reviewer-reviewee-frontend pull request #23
Opened 2023-03-17 06:28 UTC by DT-KUKU

## 상세 내용
- 리뷰 신청 로직 구현
- 리뷰 신청 msw 목업 생성
- 로그인 여부에 따른 Redirect 훅 추가
## 주의 사항
- 리뷰 신청시 주의사항
  - 제목 최대 50자 제한
  - 리부 신청 상세 내용 최대 500자 제한
  - PR URL 형식 => ( https://github.com/~/~/pull/~ , github.com/~/~/pull/~ )

2023-03-19 05:28 UTC, leeuihyun requested changes
PR 확인했습니다. 의견 및 궁금증 남겨놨습니다. 에디터와 react-hook-form에 관한 내용이 많은데 둘다 사용해본 경험이 없어서 그 부분에 대해 의문이 많게 되네요! 
고생하셨습니다!

2023-03-19 05:28 UTC, leeuihyun commented on components/ReviewRegister/RegisterForm.tsx
> +                  message: 'PR 규칙에 어긋나는 형식입니다.',
input 속성에 들어가는 register는 react-hook-form 라이브러리의 문법인 걸까요 ?

2023-03-19 05:28 UTC, leeuihyun commented on components/ReviewRegister/ReviewEditor.tsx
> +
이 부분 코드는 dynamic으로 import 해야 하는 이유가 뭔지 궁금합니다

2023-03-19 05:28 UTC, leeuihyun commented on components/ReviewRegister/ReviewRegisterType.ts
> +export interface IQuillEditorType<T> {
Quill editor 타입 하나하나 설정 .. 확인했습니다! 고생하셨습니당 👍

2023-03-19 05:28 UTC, leeuihyun commented on pages/api/reviewRegister.ts
> +};
단순 철자이긴 한데 s가 빠진 것 같습니다! 그리고 위에 msw handler을 보면 status response로 들어오는 것 같은데 return 하는 이유가 있을까요?

2023-03-19 05:28 UTC, leeuihyun commented on useHooks/useRedirectMain.tsx
> +export default useRedirectMain;
redirectMain 확인했습니다.

2023-03-19 05:28 UTC, leeuihyun commented on components/ReviewRegister/RegisterForm.tsx
> +                  message: 'PR 규칙에 어긋나는 형식입니다.',
정규식을 사용해서 검사하는 코드인것 같은데 regexp의 역할을 해주는 건지 궁금하네요

2023-03-19 05:28 UTC, leeuihyun commented on components/ReviewRegister/RegisterForm.tsx
> +  const {
registerForm은 추후에 리뷰어의 id 연동을 한 후 - 등록만 관리하는 form이 되는건가요? 혹은 등록 후 본인이 등록한 것을 수정하는 것까지 관리하시려는 걸까요 ?

2023-03-19 05:31 UTC, leeuihyun requested changes

2023-03-19 05:31 UTC, leeuihyun commented on components/ReviewRegister/ReviewEditor.tsx
> +    }
-2 를 하는 이유는 뭔가요?

2023-03-19 10:08 UTC, DT-KUKU commented on components/ReviewRegister/RegisterForm.tsx
> +                  message: 'PR 규칙에 어긋나는 형식입니다.',
네 맞습니다! register를 사용함에 따라 value, onchange를 대체할 수 있습니다.
첫 번째 값으로 구분하며 다음 값들은 규칙을 설정할 수 있습니다.

pattern은 value 에 적혀있는 정규식을 사용하며 통과하지 못한다면 message에 적혀있는 문구가 나오게 됩니다!

2023-03-19 10:24 UTC, DT-KUKU commented on components/ReviewRegister/ReviewEditor.tsx
> +
동적 임포트를 하지 않는다면 document is not defined 이라는 오류가 발생하게 됩니다. 

Quill Editor는 SSR를 지원하지 않으며 동적 임포트를 하지 않으면 호출시에 document가 없다고 나오기 때문에 동적 임포트를 통해 document가 구성된  후에 가져올 수 있도록 진행하였습니다.

기존에 React에서는 동적 임포트를 하지 않아도 바로 사용할 수 있습니다.

2023-03-19 10:24 UTC, DT-KUKU commented on components/ReviewRegister/ReviewRegisterType.ts
> +export interface IQuillEditorType<T> {
혹시 이방법말고 다른 방법에 대해서 아시는게 있을까요?? 

저는 지금와서 다시 생각해보니 `typeof` 를 사용해서 해야했나? 라는 생각이 듭니다!

2023-03-19 10:27 UTC, DT-KUKU commented on pages/api/reviewRegister.ts
> +};
s 빠진것 확인했습니다!

딱히 리턴을 하는 이유는 없습니다. 반환되는 값이 없다면 어떻게 처리할지 생각을해서 반영을 해야할거 같습니다.

2023-03-19 10:28 UTC, DT-KUKU commented on components/ReviewRegister/RegisterForm.tsx
> +  const {
현재는 수정하는것까지 포함해서 사용하려고 합니다.

수정에 대한 폼을 만드는것은 중복된 코드가 생기는거라 생각해서 하나의 폼안에서 전부 처리하려고 합니다.

2023-03-19 10:36 UTC, DT-KUKU commented on components/ReviewRegister/ReviewEditor.tsx
> +    }
getText는 현재 Editor에 아무런 값이 없어도 1이라는 값을 반환합니다.

그래서 500자 제한에 맞추기 위해 -2 처리를 했습니다.

2023-03-19 10:53 UTC, leeuihyun commented on components/ReviewRegister/ReviewEditor.tsx
> +
확인했습니다~!

2023-03-19 10:55 UTC, leeuihyun commented on components/ReviewRegister/ReviewRegisterType.ts
> +export interface IQuillEditorType<T> {
typeof를 사용하는 것도 좋은 방법일 것 같네요!

2023-03-19 10:58 UTC, leeuihyun commented on components/ReviewRegister/RegisterForm.tsx
> +  const {
넵 확인했습니다.

2023-03-20 02:34 UTC, leeuihyun commented on components/ReviewRegister/ReviewEditor.tsx
> +    }
확인했습니다!

2023-03-20 20:21 UTC, leeuihyun requested changes
props 전달에 따른 수정사항 확인했습니다.

2023-03-20 20:21 UTC, leeuihyun commented on pages/register.tsx
> +      },
getServerSideprops return props를 info 객체로 주셨는데 Register page에서는 reviewerInfo를 사용하고 있는데 에러가 나지 않나요 ?

2023-03-21 01:09 UTC, DT-KUKU commented on components/ReviewRegister/ReviewEditor.tsx
>      trigger('content');
기존에는 -2 를 해서 같다라는 표시는 하지 않았는데 기존에 로직이 값이 없어도 1 나오는걸 생각해서 

1로 변경하고 같다는 표시로 변경했습니다.

2023-03-21 01:09 UTC, DT-KUKU commented on pages/register.tsx
> +      },
이 부분 오류를 확인했습니다!!.. 

props 부분을 info => reviewerInfo 로 수정 예정입니다!

2023-03-21 02:24 UTC, leeuihyun commented on pages/register.tsx
> +      },
넵 확인했습니다~

2023-03-21 02:25 UTC, leeuihyun approved these changes
고생하셨습니다~!

2023-03-21 02:49 UTC, merged