[#36] 헤더 구조 수정
neonadeuri/reviewer-reviewee-frontend pull request #38
Opened 2023-03-28 16:35 UTC by DT-KUKU

## 상세 내용
- Semantic Tag로 수정
- Header 구조 변경
- 드롭다운 리스트 위치 수정
- 페이지 연결 

## 주의 사항
- 외부 클릭시 드롭다운 리스트 OFF를 할지 미정
- 반응형 적용 여부 미정

2023-03-29 08:44 UTC, leeuihyun requested changes
처음 제가 만들 때 명확하게 정해진 부분이 없어서 정말 띄워놓기만 한 부분이었는데 디자인 훨신 깔끔해지고 좋은 것 같습니다! 

- 반응형에 대한 부분은 드롭다운까지 반응형을 할 필요가 크지 않다고 생각합니다.
- 외부 클릭시 dropdown 을 OFF 하는 부분은 확실히 OFF하는게 나아 보입니다.

2023-03-29 08:44 UTC, leeuihyun commented on components/Header.tsx
> +      <header className="w-full h-24 flex justify-center text-4xl">
semantic tag로 분류하신 부분 확인했습니다. 부모 div -> header가 아닌 자식 div에 header를 하신 이유가 있을까요 ?

2023-03-29 08:44 UTC, leeuihyun commented on components/HeaderSub/HeaderDropDown.tsx
> +    <div className="z-100 bg-white divide-y divide-gray-100 rounded-lg shadow w-40 dark:bg-gray-700 absolute mt-3 left-2/4 -translate-x-2/4 top-12 text-center">
`-translate-x-2/4` 부분이 의미하는 건 어떤건가요 ?

2023-03-29 11:57 UTC, DT-KUKU commented on components/HeaderSub/HeaderDropDown.tsx
> +    <div className="z-100 bg-white divide-y divide-gray-100 rounded-lg shadow w-40 dark:bg-gray-700 absolute mt-3 left-2/4 -translate-x-2/4 top-12 text-center">
부모 요소 기준 가운데 정렬을 하기 위해 사용했습니다!

2023-03-29 11:58 UTC, DT-KUKU commented on components/Header.tsx
> +      <header className="w-full h-24 flex justify-center text-4xl">
캐러셀 부분을 포함해서 header라고 정하는게 맞는가 라는 생각을 했습니다.

그래서 로고 부분과 유저 버튼이 있는 부분을 header 태그로 변경했습니다!

2023-03-29 12:19 UTC, leeuihyun commented on components/Header.tsx
> +      <header className="w-full h-24 flex justify-center text-4xl">
이 부분이 모호한 부분인 것 같긴 하네요. 확인했습니다~!

2023-03-29 14:01 UTC, DT-KUKU commented on components/Header.tsx
> +      <header className="w-full h-24 flex justify-center text-4xl">
추후에 캐러셀로 작업을 할때 분리해서 관리할지를 이야기 해보시죠!

2023-03-30 03:46 UTC, leeuihyun approved these changes
외부 OFF 확인했습니다~!

2023-03-30 04:09 UTC, merged