[#39] 리뷰 상세정보 모달 API 구현 및 연결
neonadeuri/reviewer-reviewee-frontend pull request #42
Opened 2023-03-30 09:26 UTC by DT-KUKU

## 상세 내용
- index 임시 버튼 삭제
- reviewModal API 추가
- reviewModal msw 추가
- reviewModal Type 추가
- reviewModal 연결

## 주의 사항
- 리뷰 목록 데이터 imageUrl 데이터 img로 임시 변경

2023-03-31 07:47 UTC, leeuihyun requested changes
궁금증 및 리뷰 남겼습니다 !

2023-03-31 07:47 UTC, leeuihyun commented on components/ReviewModal/ReviewModal.tsx
> +              </>
승인에 관한 부분은 수락을 했을 경우 그 이후에 보여주는 게 맞지 않을까요 ?

2023-03-31 07:47 UTC, leeuihyun commented on components/ReviewModal/ReviewModal.tsx
> +              <span className="ml-2">{username}</span>
span, p를 구분해서 쓰시는데 p와 span의 차이점은 분명히 존재하지만 이 코드에서는 어떤 걸 사용하든 큰 차이점이 없을 것 같아서 어떤 것을 기준으로 나눠서 사용하신건지 궁금합니다

2023-03-31 07:47 UTC, leeuihyun commented on components/ReviewModal/ReviewModal.tsx
> +                <ButtonWrapper>리뷰 수정</ButtonWrapper>
수정 버튼 이벤트로 이동하는 부분은 추후에 넣으시는 걸까요 ?

2023-03-31 07:47 UTC, leeuihyun commented on components/ReviewModal/ReviewModal.tsx
> +  const { data } = useQuery<IReviewModalApiDetailType>({
어제 얘기 나눴던 이런 쿼리 방식을 명확하게 어떤 식으로 하는 것이 좋을까요? 만약 재사용성이 없는 query라면 현재 경호님이 작성하신 방법처럼 그대로 넣어도 되고, 혹은 한 파일안에서 function을 만들어서 사용하는 것도 괜찮을 것 같습니다. 

이전에 제가 query 폴더를 만들어서 관리한 부분은 생각해보니 의미 없는 모듈화를 한 것 같다는 생각이 들더라구요

2023-03-31 14:38 UTC, DT-KUKU commented on components/ReviewModal/ReviewModal.tsx
> +              </>
그게 맞는거 같습니다. 추후 리뷰어의 수락 여부에 관한 값을 전달받으면 말해주신대로 처리하겠습니다. 현재는 그걸 나누는 기준 값이 존재 하지 않아서 구분하기는 애매한거 같습니다.

2023-03-31 14:39 UTC, DT-KUKU commented on components/ReviewModal/ReviewModal.tsx
> +                <ButtonWrapper>리뷰 수정</ButtonWrapper>
아뇨 제가 추가하는 걸 빼먹은듯 합니다. 이번에 추가해놓겠습니다!

2023-03-31 14:41 UTC, DT-KUKU commented on components/ReviewModal/ReviewModal.tsx
> +  const { data } = useQuery<IReviewModalApiDetailType>({
저희가 useQuery를 사용하는 부분을 Custom Hook으로 빼는건 어떠신가요??

훅으로 변경한다면 통일되게 사용할 수 있고 더 깔끔하게 사용할 수 있을거 같습니다!

2023-04-01 04:23 UTC, leeuihyun commented on components/ReviewModal/ReviewModal.tsx
> +  const { data } = useQuery<IReviewModalApiDetailType>({
알겠습니다!

2023-04-01 04:30 UTC, leeuihyun requested changes

2023-04-01 04:30 UTC, leeuihyun commented on components/ReviewModal/ReviewModifyLink.tsx
> +      리뷰 수정
리뷰 수정 버튼의 위치만 변경하신 것 같은데, 처음 quill을 가져오고 글자수가 0으로 나오던 부분이 해결된 다른 이유가 있을까요 ?

2023-04-01 14:47 UTC, DT-KUKU commented on components/ReviewModal/ReviewModifyLink.tsx
> +      리뷰 수정
원인을 파악했습니다. 정리해서 말씀드리도록 하겠습니다.

2023-04-02 03:46 UTC, leeuihyun approved these changes

2023-04-02 04:57 UTC, merged