[#43] 리뷰 신청 페이지 에디터 에러 멘트 로직 수정 및 통합관리로 수정 작업
neonadeuri/reviewer-reviewee-frontend pull request #45
Opened 2023-04-02 12:14 UTC by DT-KUKU

## 상세 내용
- ReviewRegister register 생성 위치 useEffect로 변경
- ReviewRegister error 문구 즉시 반영 가능하도록 변경
- 리뷰 등록/수정 이동시 사용되는 Link의 as 삭제
- InformationForm Loading 컴포넌트 추가
- color, font weight, border radius 통합관리로 변경
- slate, stone => gray, neutral 로 변경
- rose color => red로 변경
- Image tag rounded-full => rouneded 50%로 변경

## 주의 사항
- ReviewRoleButtonGroup => 커스텀으로 변경시 우선순위로 인해서 color가 적용되지 않는 부분 확인  그에 따른 코드 일부 수정
- HookFormDropDown => 커스텀으로 변경시 우선순위로 인해서 color가 적용되지 않는 부분 확인  그에 따른 코드 일부 수정

2023-04-03 10:03 UTC, leeuihyun requested changes
통합 하시느라 고생 많으셨습니다! 전부 확인했고 radius같은 부분이 잘 통합이 안되어있다고 생각은 했었는데 확실히 디자인적으로 좋네요. 

고생하셨습니다.

2023-04-03 10:03 UTC, leeuihyun reviewed
font-weight 부분까지는 안해도 될 것 같습니다.

2023-04-03 10:05 UTC, leeuihyun commented
우선 순위에 따라 적용되지 않는 부분이 있다고 말씀하셨는데 어떤 부분에서 우선순위에 따라 적용이 안되셨는지 궁금합니다.

2023-04-03 10:07 UTC, leeuihyun commented on components/userInfomation/HookFormDropDown.tsx
> +          className={clsx('w-full border-2 rounded-radius-m mt-0.5 overflow-y-auto h-44', {
우선 순위에 따라 적용되지 않는 부분이 있다고 말씀하셨는데 어떤 부분에서 우선순위에 따라 적용이 안되셨는지 궁금합니다.

2023-04-04 02:29 UTC, DT-KUKU commented on components/Main/ReviewerCard.tsx
>              href={{
as 와 NextJS에서 제공하는 shallow 옵션도 사용해 봤는데 전부 새로고침시 문제가 발생했습니다.

지금은 지우는 형식으로 가지만 추후에 API콜을 통해 데이터를 받아와 useEffect로 데이터를 채워넣는 형식도 고려를 해봐야할듯 합니다.

2023-04-04 02:37 UTC, DT-KUKU commented on components/userInfomation/HookFormDropDown.tsx
> +          className={clsx('w-full border-2 rounded-radius-m mt-0.5 overflow-y-auto h-44', {
예를 들어 설명하자면 기존에 bg-black 에서 특정 값일 때 bg-blue-500으로 변경한다고 하면 기존에 적용된 bg-black 부분이 사라지고 bg-blue-500이 적용이 되었습니다. 

하지만 커스텀으로 변경후에는 엘리먼트에 특정 컬러가 지정되어 있으면 덮어씌우려고해도 적용이 되지 않는 부분을 확인 했습니다.
```html
 text-c-black p-2 h-10 w-full border-solid text-neutral300
```

2023-04-04 04:53 UTC, leeuihyun commented on components/userInfomation/HookFormDropDown.tsx
> +          className={clsx('w-full border-2 rounded-radius-m mt-0.5 overflow-y-auto h-44', {
넵 확인했습니다.

2023-04-04 05:13 UTC, leeuihyun commented on components/Main/ReviewerCard.tsx
>              href={{
이 부분에 대해서 몇가지 테스트를 해봤는데 전부 새로고침시 문제가 발생하네요. 
최소한의 데이터만 query로 넘기고 useEffect로 데이터를 채워넣는 형식이 url, seo 관점에서 봤을 때는 괜찮아 보입니다

2023-04-04 06:16 UTC, leeuihyun commented on components/ReviewRegister/RegisterForm.tsx
> +  useEffect(() => {
확인했습니다.

2023-04-04 06:17 UTC, leeuihyun approved these changes
고생하셨습니다~!

2023-04-04 07:55 UTC, merged