Feature/3
neonadeuri/reviewer-reviewee-frontend pull request #5
Opened 2023-02-28 16:33 UTC by DT-KUKU

## 상세 내용

- 리뷰어 등록 페이지 퍼블리싱

## 주의 사항

- 리뷰어 등록 폼에 대한 구체적인 틀이 정해지면 추후 수정

2023-03-03 05:12 UTC, leeuihyun requested changes
전체적으로 디자인 너무 깔끔하게 잘 만드신 것 같습니다.

메인페이지의 `border` 색상도 경호님이 작성하신 코드 참조해서 조금 수정해보려합니다.

의문 및 사전에 얘기했던 코드 공유, 생각 남겨놨습니다.

2023-03-03 05:12 UTC, leeuihyun commented on components/userInfomation/ReviewerRegisterModal.tsx
> +  return (
모달이 켜진 후 화면 스크롤 밑은 색이 안 변하는 이슈가 제 화면에서는 있는데 처음 설정이 잘못된 부분인건지 후에 한번 회의해야할 것 같습니다. 
제 화면에서만 그런건지는 정확하게는 모르겠습니다

2023-03-03 05:12 UTC, leeuihyun commented on components/userInfomation/informationType.ts
> +}
Ts interface 파일 확인했습니다! 

우선 메인페이지에 들어갈 내용이 명확하지 않아서 저는 아직 만들지는 않았고,
props에 바로 type 지정을 해서 사용을 해놨는데 

추후에 이런 형식으로 바꾸겠습니다.

깔끔하게 타입을 볼 수 있는 것 같아서 좋네요!

2023-03-03 05:12 UTC, leeuihyun commented on components/userInfomation/ReviewerDropDown.tsx
> +          })}>
이 코드는 `drop = true` 일 때만 반영되는 코드 아닌가요 ? 
`true and 연산자`로 들어간 `ul` 내부 className의 `clsx`에 `!drop`코드가 먹는지 궁금합니다.

2023-03-03 13:48 UTC, DT-KUKU commented on components/userInfomation/ReviewerRegisterModal.tsx
> +  return (
제 화면에서도 그렇게 동작합니다.

이건 추후에 초기 세팅에 대해서 다시한번 이야기하고 조정해보는게 좋을거 같습니다!

2023-03-03 13:49 UTC, DT-KUKU commented on components/userInfomation/ReviewerDropDown.tsx
> +          })}>
확인해본 결과 반영이 안되는걸 확인했습니다!.. ㅎ

지금은 지운 상태로 반영했습니다. 확인 감사합니다👍

2023-03-04 08:55 UTC, leeuihyun commented on components/userInfomation/ReviewerRegisterModal.tsx
> +  return (
넵 알겠습니다

2023-03-04 08:56 UTC, leeuihyun commented on components/userInfomation/ReviewerDropDown.tsx
> +          })}>
넵 확인했습니다.

2023-03-10 09:29 UTC, leeuihyun requested changes
수정 확인했습니다. 전체적으로 확인하며 리뷰 남겼습니다!

2023-03-10 09:29 UTC, leeuihyun commented on components/userInfomation/informationType.ts
> +  data: Omit<IUserGetType, 'userInfo'>;
Omit 속성은 사용한 경험이 없어서 잘 몰랐는데 저런 방식으로 원타입에서 제거해서 사용하는 형식이군요. 
좋은 타입 사용인 것 같습니다! 알아갑니다 👍

2023-03-10 09:29 UTC, leeuihyun commented on components/userInfomation/ReviewerDropDown.tsx
> +          }
이 부분은 중복 검사 로직일까요?

2023-03-10 09:29 UTC, leeuihyun commented on components/userInfomation/ReviewerRegisterModal.tsx
> +
Query의 staleTime을 어떤 기준을 잡고 설정하시는지 궁금합니다

2023-03-10 09:29 UTC, leeuihyun commented on components/userInfomation/ReviewerRegisterModal.tsx
> +  }
validation 함수와 isLoading을 이용하는 부분 확인했습니다. 공통으로 로딩컴포넌트 현재 만들어놔서 추후에 그 컴포넌트 이용하면 좋을 것 같습니다~!

2023-03-10 09:29 UTC, leeuihyun commented on pages/_app.tsx
> +
제 코드에서는 명확하게 말할 순 없지만 새로고침 후 특정 경우에 import로 가져오면 useQuery가 msw 라이브러리 보다 먼저 실행되서 오류가 발생하더라구요! require로 변경했더니 그런 오류는 사라졌습니다. 현재 코드는 require로 변경해 놨습니다!

2023-03-10 09:29 UTC, leeuihyun commented on components/userInfomation/InformationForm.tsx
> +  };
저번에 정한 react-hot-toast 사용법 확인했습니다. 실제로 연동해서 보니 깔끔한 것 같네요!

2023-03-11 06:51 UTC, DT-KUKU commented on components/userInfomation/ReviewerDropDown.tsx
> +          }
맞습니다!

똑같은걸 선택할 경우에 맨앞으로 이동시키록 해놨습니다.

해당 부분을 추후에는 사용자가 선택을 하면 드롭다운에서 선택한걸 제외하고 보여주도록 하면 어떨까 생각하고 있습니다!.

현재 방식과 지금 방식중 어떤게 더 좋을까요? 의견 부탁드립니다!

2023-03-11 06:59 UTC, DT-KUKU commented on components/userInfomation/ReviewerRegisterModal.tsx
> +
staleTime은 온전히 사용자의 선택에 달려있는거 같습니다!

저는 아래 블로그를 보고 해당 시간을 설정했습니다!
=> https://tkdodo.eu/blog/react-query-as-a-state-manager#customize-staletime

2023-03-11 06:59 UTC, DT-KUKU commented on components/userInfomation/ReviewerRegisterModal.tsx
> +  }
머지되면 바로 수정하겠습니다 ~~

2023-03-11 07:00 UTC, DT-KUKU commented on pages/_app.tsx
> +
저는 아직까지는 해당 오류가 발생하지 않았습니다.

머지할 때 해당 부분은 의현님 코드를 적용하는걸로 하면 될거 같습니다!

2023-03-11 08:33 UTC, leeuihyun commented on components/userInfomation/ReviewerDropDown.tsx
> +          }
제외하기 보다는 중복된 것을 골랐을 때 지금과 같은 로직으로 맨앞이동과 유저에게 알림을 보여주는 방식이 좋을 것 같습니다!

맨 처음에 리뷰어의 스택을 받아온 화면에서는 중복으로 추가가 되더라구요. 임시로 해놓으신 건지, 수정이 필요한 부분인지 확인해주시면 좋을 것같습니다!

2023-03-11 08:35 UTC, leeuihyun commented on components/userInfomation/ReviewerRegisterModal.tsx
> +
넵넵 확인했습니다~!

2023-03-12 10:03 UTC, leeuihyun approved these changes
고생하셨습니다~!

2023-03-12 10:03 UTC, merged

2023-03-13 04:53 UTC, DT-KUKU commented on components/userInfomation/ReviewerDropDown.tsx
> +          }
해당 부분을 완벽하게 확인하지 못했네요! 추후 수정하겠습니다!