[#60] 마이 페이지 모달 드롭다운 컴포넌트 분리
neonadeuri/reviewer-reviewee-frontend pull request #62
Opened 2023-04-12 07:26 UTC by DT-KUKU

## 상세 내용
- 기존에 사용되던 HookFormDropDown, ReviewerDropDown 컴포넌트 삭제
- DropDown 컴포넌트 => Select 와 Skill 컴포넌트로 분리
- 리뷰어 등록 및 수정 mutate 두개의 mutate로 분리
- Select 와 Skill은 useState로 input 과 textarea는 ReactHookForm 으로 관리
- 사용되지 않는 타입 삭제

2023-04-13 06:12 UTC, leeuihyun requested changes
수정이 엄청 많네요..! 분리하신 부분 및 말씀해주신 부분 모두 확인했고 의견 달아놨습니다 고생하셨습니다.!

2023-04-13 06:12 UTC, leeuihyun commented on components/UserInformation/ReviewModalDropDownSelect.tsx
> +              </li>
key에 index를 넣는 것은 추후에 오류가 발생할 수 있는데 이 부분을 수정하는 건 어떨까요 ?

2023-04-13 06:12 UTC, leeuihyun commented on components/UserInformation/informationType.ts
> +export interface IUserInformationType extends IUserType {
일관성 있는 타입명 수정 확인했습니다. 수정해야지.. 하고 생각은 하고 있었는데 좋습니다!

2023-04-13 06:12 UTC, leeuihyun commented on components/UserInformation/ReviewModalDropDownSelect.tsx
> +function ReviewModalDropDownSelect({ name, select, setState, itemList, register }: IReviewModalDropDownSelectProps) {
직무, 경력에 관한 분리 확인했습니다. 확실히 직관적으로 확인이 가능한 것 같습니다.

2023-04-13 06:12 UTC, leeuihyun commented on components/UserInformation/ReviewModalDropDownSkill.tsx
> +const MAXSKILL = 3;
이런 상수들은 constants와 같은 폴더 내에서 관리하는 것도 좋다고 들었는데 지금 바로 수정할 부분은 아니지만 어떻게 생각하시는지 궁금합니다

2023-04-13 06:12 UTC, leeuihyun commented on components/UserInformation/queries/getReviewerQuery.tsx
> +    queryKey: [REVIEWER, userName],
경호님이 주의사항에 작성해주신 부분이 이 부분 맞을까요 ? (아니라면 말씀해주세요.)
필요없을 것 같습니다. reviewer과 같은 부분이 겹친다면 어떤 모달인지에 대한 것으로 네이밍을 하는게 더 낫지 않을까 생각합니다!

2023-04-13 06:34 UTC, DT-KUKU commented on components/UserInformation/ReviewModalDropDownSkill.tsx
> +const MAXSKILL = 3;
저도 이부분을 이야기하고 싶었습니다! 상수가 많아지면 하나의 파일에서 전부 관리를 하고 주석으로 영역을 정해서 보면 편리할 듯합니다.

예를 들어
```typescript
/* ReviewModal */
const MAXSKILL = 3;
const MAXSELECT = ~~;
const ~~ 
```

2023-04-13 06:35 UTC, DT-KUKU commented on components/UserInformation/queries/getReviewerQuery.tsx
> +    queryKey: [REVIEWER, userName],
이 부분 맞습니다!. userName은 삭제하도록 하겠습니다!!

2023-04-13 07:49 UTC, leeuihyun commented on components/UserInformation/ReviewModalDropDownSkill.tsx
> +const MAXSKILL = 3;
좋은 것 같습니다 조만간 관리하는 이슈 만들어보겠습니다

2023-04-14 04:48 UTC, leeuihyun commented on components/UserInformation/ReviewModalDropDownSelect.tsx
> +              </li>
확인했습니다~!

2023-04-14 04:48 UTC, leeuihyun approved these changes

2023-04-14 05:39 UTC, merged